# Generated by Django 5.2.9 on 2026-01-02 16:16

import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта клиента')),
                ('review', models.TextField(verbose_name='Отзыв клиента')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (звезды)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без имени', max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='Владелец')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+996000000000', max_length=128, region='KG', verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='avatars/')),
                ('engine', models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Гибрид', 'Гибрид'), ('Прочий', 'Прочий')], default='Бензин', max_length=15, verbose_name='Тип двигателя')),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объем двигателя (л)')),
                ('number_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('engine_check_1', models.DateField(blank=True, null=True, verbose_name='Очистка двигателя — 1 раз')),
                ('engine_check_2', models.DateField(blank=True, null=True, verbose_name='Очистка двигателя — 2 раз')),
                ('engine_check_3', models.DateField(blank=True, null=True, verbose_name='Очистка двигателя — 3 раз')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.group', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
    ]
