# Generated by Django 5.2.6 on 2025-09-27 11:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Марка"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "engine_capacity",
                    models.IntegerField(blank=True, null=True, verbose_name="Обьем"),
                ),
                (
                    "year",
                    models.IntegerField(blank=True, null=True, verbose_name="Год"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Причина"),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("Бензин", "Бензин"),
                            ("Диз топливо", "Диз топливо"),
                            ("Гибрид", "Гибрид"),
                            ("Прочий", "Прочий"),
                        ],
                        default="Бензин",
                        max_length=15,
                        verbose_name="Тип двигателя",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+996000000000",
                        max_length=128,
                        region="KG",
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "join_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Транспортное средство",
                "verbose_name_plural": "Транспортные средства",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Без имени", max_length=100)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
