# Generated by Django 5.2.6 on 2025-09-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="avatar",
            field=models.ImageField(null=True, upload_to="Авто_фото"),
        ),
        migrations.AlterField(
            model_name="cars",
            name="engine_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Объем двигателя (л)",
            ),
        ),
    ]
