# Generated by Django 5.2.6 on 2025-09-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_cars_avatar_alter_cars_engine_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cars.group",
                verbose_name="Категория",
            ),
        ),
    ]
