# Generated by Django 5.2.6 on 2025-09-28 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_cars_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="number_plate",
            field=models.CharField(
                default="01KG001AAA",
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_number_plate",
                        message="Номер должен быть в формате 01KG001AAA",
                        regex="^\\d{2}KG\\d{3}[A-Z]{3}$",
                    )
                ],
                verbose_name="Гос. номер",
            ),
        ),
    ]
