# Generated by Django 5.2.6 on 2025-09-28 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_cars_number_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="engine_check_1",
            field=models.DateField(
                default=datetime.date(2025, 9, 28),
                verbose_name="Очистка двигателя — 1 раз",
            ),
        ),
        migrations.AddField(
            model_name="cars",
            name="engine_check_2",
            field=models.DateField(
                blank=True, null=True, verbose_name="Очистка двигателя — 2 раз"
            ),
        ),
        migrations.AddField(
            model_name="cars",
            name="engine_check_3",
            field=models.DateField(
                blank=True, null=True, verbose_name="Очистка двигателя — 3 раз"
            ),
        ),
    ]
