# Generated by Django 5.2.6 on 2025-09-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_cars_engine_check_1_cars_engine_check_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="cars",
            name="review",
            field=models.TextField(blank=True, null=True, verbose_name="Отзыв клиента"),
        ),
    ]
