# Generated by Django 5.2.6 on 2025-09-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_cars_is_active_cars_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Электронная почта"
            ),
        ),
    ]
