# Generated by Django 5.2.6 on 2025-09-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_cars_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="owner",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Владелец"
            ),
        ),
    ]
