# Generated by Django 5.2.6 on 2025-09-28 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_cars_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="engine_check_2",
        ),
        migrations.RemoveField(
            model_name="cars",
            name="engine_check_3",
        ),
        migrations.AlterField(
            model_name="cars",
            name="engine_check_1",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Очистка двигателя — 1 раз",
            ),
        ),
    ]
