# Generated by Django 5.2.6 on 2025-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0010_remove_cars_engine_check_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="engine_check_2",
            field=models.DateField(
                blank=True, null=True, verbose_name="Очистка двигателя — 2 раз"
            ),
        ),
        migrations.AddField(
            model_name="cars",
            name="engine_check_3",
            field=models.DateField(
                blank=True, null=True, verbose_name="Очистка двигателя — 3 раз"
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="engine_check_1",
            field=models.DateField(
                blank=True, null=True, verbose_name="Очистка двигателя — 1 раз"
            ),
        ),
    ]
