# Generated by Django 5.2.6 on 2025-09-28 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_cars_engine_check_2_cars_engine_check_3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="Авто_фото"),
        ),
        migrations.AlterField(
            model_name="cars",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="cars",
            name="engine",
            field=models.CharField(
                choices=[
                    ("Бензин", "Бензин"),
                    ("Дизель", "Дизель"),
                    ("Гибрид", "Гибрид"),
                    ("Прочий", "Прочий"),
                ],
                default="Бензин",
                max_length=15,
                verbose_name="Тип двигателя",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cars.group",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="number_plate",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер должен быть в формате 01KG001AAA",
                        regex="^\\d{2}KG\\d{3}[A-Z]{3}$",
                    )
                ],
                verbose_name="Гос. номер",
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год выпуска"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                default="Без имени", max_length=100, verbose_name="Название категории"
            ),
        ),
    ]
