# Generated by Django 5.2.6 on 2025-09-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0012_alter_cars_avatar_alter_cars_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя клиента")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Почта клиента"),
                ),
                ("review", models.TextField(verbose_name="Отзыв клиента")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Отзыв клиента",
                "verbose_name_plural": "Отзывы клиентов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="cars",
            name="review",
        ),
    ]
