# Generated by Django 5.2.6 on 2025-09-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0013_clientreview_remove_cars_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientreview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name="Оценка (звезды)"
            ),
        ),
    ]
