# Generated by Django 5.2.6 on 2025-09-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0015_alter_cars_number_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="number_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
